---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crypto-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "crypto-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "crypto-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "crypto-api.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: {{ .Values.service.protocol  }}
          livenessProbe:
            httpGet:
              path: /healthz/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /healthz/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

